### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by perrin4869**
Took advantage of touching the code, upgraded all the dependencies and made sure all the linting works :)
Appreciate it if you could publish the changes to npm.

Also, would be cool if you setup greenkeeper, travis, coveralls.
Thanks!

### CODE REVIEW

**Comment by jurassix** [comment]
Thanks for the PR. Published to npm as v0.2.0

**Comment by jurassix** [comment]
I can make you a collaborator if you wanna help with the push to greenkeeper, travix, coneralls, etc? If not no worries, I'll try to set this up for all my projects.

**Comment by perrin4869** [comment]
Yeah why not, I might have time tonight or tomorrow :)

**Comment by jurassix** [comment]
Added as collaborator. Thanks for the help!

**Comment by perrin4869** [comment]
@jurassix I tried adding greenkeeper, coveralls and travis support yesterday, but you do need to be the owner of the repo in order to do that after all. It's not complicated at all though, once you enable them I'll do the configuration. It's just a matter of switching support on

**Comment by jurassix** [comment]
Ok thanks for the try. I'll get on this soon.

**Pull request merged**
