### PR TITLE
Switch from babel 5 to 6

### PR DESCRIPTION
**Pull request by martindederer**
Babel 6 changed the way it exports "default". See [here](https://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default) for details. Do you think it's necessary to use [babel-plugin-add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports) to keep backwards compatibility?

### CODE REVIEW

**Comment by jurassix** [comment]
@martindederer We can just do a minor version bump to v0.1.0 and be fine. I don't see a need for the backwards compat fix.

**Comment by martindederer** [comment]
Just curious, are there any blockers left preventing the merge of this PR or are you "just" busy with real work? :)

**Comment by jurassix** [comment]
@martindederer published to npm as v0.1.1

**Comment by jurassix** [comment]
Been busy :smile:

**Pull request merged**
